name = Matugen Dynamic
bg = {{colors.background.default.hex}}
panel = {{colors.surface_container_high.default.hex}}
border = {{colors.outline.default.hex}}
fg = {{colors.on_background.default.hex}}
dim = {{colors.outline.default.hex}}
accent = {{colors.primary.default.hex}}
cursor = {{colors.surface_container.default.hex}}
selection = {{colors.secondary_container.default.hex}}
statusbar = {{colors.surface_variant.default.hex}}
status_fg = {{colors.on_surface_variant.default.hex}}
mode_fg = {{colors.on_primary.default.hex}}
mode_bg = {{colors.primary.default.hex}}
pri_a = {{colors.error.default.hex}}
pri_b = {{colors.tertiary.default.hex}}
pri_c = {{colors.secondary.default.hex}}
pri_d = {{colors.primary.default.hex}}
pri_other = {{colors.secondary_fixed.default.hex}}
project = {{colors.secondary.default.hex}}
context = {{colors.tertiary.default.hex}}
due = {{colors.tertiary_container.default.hex}}
overdue = {{colors.error.default.hex}}
today = {{colors.error_container.default.hex}}
done = {{colors.surface_container_highest.default.hex}}
selected = {{colors.secondary_container.default.hex}}
matched = {{colors.primary_container.default.hex}}
