set -g clock-mode-colour "#d8c3ab"

# copy mode
set -g mode-style 'fg=black bg=red bold'

# panes
set -g pane-border-style 'fg=black'
set -g pane-active-border-style 'fg=yellow'

# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style ''

set -g status-left-length 40
set -g status-left "#[fg=#3b2e1d,bg=default]#[fg=#f5dfc6,bg=#3b2e1d] #S#[fg=#3b2e1d,bg=default] "

set -g status-right-length 60
set -g status-right "#[fg=#3b2e1d,bg=default,bold]#[fg=#f5dfc6,bg=#3b2e1d,bold]%Y-%m-%d#[fg=#3b2e1d,bg=default,bold] #[fg=#3b2e1d,bg=default,bold]#[fg=#f5dfc6,bg=#3b2e1d,bold] %H:%M#[fg=#3b2e1d,bg=default,bold] #[fg=#3e2e16,bg=default,bold]#[fg=#fadebc,bg=#3e2e16,bold]󰁹 #(cat /sys/class/power_supply/BAT0/capacity)#[fg=#3e2e16,bg=default,bold]"

set -g window-status-current-format '#[fg=#d8c3ab,bg=default,bold]#I #[fg=white,bold]#W #[fg=#d3c4b4,bold]#F'
set -g window-status-format '#{?window_bell_flag,#[fg=#ffb4ab],#[fg=#737373]}#I #W #{?window_bell_flag,,#F}'

# messages
set -g message-style 'fg=#ffdad6,bg=#690005,bold'

set -g window-status-bell-style ''
