[default]
time = 1.5
;image-base-dir =
;image-opacity = 1.0
;width = 248
;height = 232
;padding = 24
y-offset = 0.5
x-offset = 0.5
border-radius = 10
border-width = 0
;block-height = 10
;block-spacing = 2
;block-count = 20
fade-in = 0.2
fade-out = 0.3

background = {{colors.primary.dark.rgba | set_alpha: 0.8}}
border-color = {{colors.outline.dark.rgba | set_alpha: 0.8}}
bar-fg-color = {{colors.background.dark.rgba | set_alpha: 0.8}}

